knocklabs/telegraph

- examples/playground/package.json
- package.json
- packages/core/package.json
- packages/postcss-config/package.json
- packages/prettier-config/package.json
- packages/tailwind-config/package.json
- packages/typography/package.json
- packages/vite-config/package.json
- packages/vitest-config/package.json
- Set `manypkg.defaultBranch` to `main` so that package repository urls are correct
> fix: correct repository url with manypkg declaration in root package json

- .changeset/odd-shrimps-study.md
- package.json
The all flag was missing from the release command causing it to error
> fix: yarn release command needs all flag

- .changeset/cold-llamas-report.md
- package.json
> fix: yarn release command all to Rpt

- .changeset/little-bobcats-wait.md
- README.md
- packages/core/README.md
- packages/core/package.json
- packages/postcss-config/README.md
- packages/prettier-config/README.md
- packages/tailwind-config/README.md
- packages/tokens/README.md
- packages/typography/README.md
- packages/typography/package.json
- packages/vite-config/README.md
- packages/vitest-config/README.md
- Updates main repo readme
- Updates each package readme with relevant info
> feat: update readme files

- packages/button/README.md
- packages/icon/README.md
Usage docs for the Button and Icon components
> docs: readme file for button & icon packages

- .changeset/kind-mails-build.md
- package.json
- packages/button/src/Button/Button.tsx
> fix: button whitespace wrapping

- .changeset/modern-baboons-sip.md
- packages/modal/src/Modal/Modal.stories.tsx
- packages/modal/src/Modal/Modal.tsx
- Updates button sizing in modal to match design system correctly
[KNO-6124](https://linear.app/knock/issue/KNO-6124/[telegraph]-modal-button-sizing-issues)
> fix: update modal button sizing

- .changeset/light-hornets-serve.md
- packages/layout/src/Box/Box.constants.ts
- packages/layout/src/Box/Box.styles.css
- packages/tokens/src/index.ts
- packages/tokens/src/tokens/border-style.ts
- Adds `border-style` values to tokens
- Adds support for border style to layout components
[KNO-6154](https://linear.app/knock/issue/KNO-6154/[telegraph]-box-dashed-border)
> feat: add border style support to layout components

- package.json
- turbo.json
- Cleans up remaining references to examples
[KNO-6150](https://linear.app/knock/issue/KNO-6150/[telegraph]-cleanup-examples-removal)
> chore: cleanup examples removal

- packages/radio/src/RadioCards/RadioCards.tsx
> fix: radio cards tweaks

- .changeset/silent-suns-listen.md
- packages/helpers/src/components/RefToTgphRef/RefToTgphRef.tsx
- packages/layout/src/Box/Box.constants.ts
- packages/layout/src/Box/Box.styles.css
- packages/menu/.eslintrc.js
- packages/menu/README.md
- packages/menu/package.json
- packages/menu/postcss.config.mjs
- packages/menu/src/Menu/Menu.stories.tsx
- packages/menu/src/Menu/Menu.tsx
- packages/menu/src/Menu/index.ts
- packages/menu/src/default.css
- packages/menu/tailwind.config.mts
- packages/menu/tsconfig.json
- packages/menu/vite.config.mts
- packages/menu/vitest.config.mts
- packages/menu/vitest.d.ts
- yarn.lock
- Utilizes Radix's menu component
- Adds `shadow` support to `<Box/>` component
- Fixes ordering of `RefToTgphRef` props to avoid collisions
[KNO-6142](https://linear.app/knock/issue/KNO-6142/[telegraph]-menu-component)
> feat: menu component

- .changeset/chilly-lobsters-refuse.md
- packages/tokens/src/tokens/family.ts
Adds additional fallback sans serif and mono fonts
> feat: update default font family stacks

- .changeset/ninety-eels-bake.md
- packages/button/src/Button/Button.constants.ts
- packages/combobox/src/Combobox/Combobox.tsx
- Fixes issue with `Button` component not having a background color set for the `outline` variant.
- Fixes issue where removing a tag from a multi-select combobox would trigger a "submit". 
- Fixes height issue on placeholder
- Applies background color to content menu.
- Fixes issue with smooth height animation jumping by using min-height instead of height.
- Sets maxHeight for Options so we get a scrollbar when the options don't fit. 
- Fix not being able to tab in / out of the combobox.
[KNO-6298](https://linear.app/knock/issue/KNO-6298/[telegraph]-combobox-integration-bugs)
> fix: combobox fixes & improevements after integration

- .changeset/mighty-crews-pay.md
- packages/button/src/Button/Button.constants.ts
- packages/button/src/Button/Button.tsx
- packages/icon/src/Icon/Icon.tsx
- packages/tag/src/Tag/Tag.constants.ts
- packages/tag/src/Tag/Tag.stories.tsx
- packages/tag/src/Tag/Tag.tsx
* Size 0 tag
* Sets different left padding
* Cannot have `onCopy` or `onRemove`
> feat: introduce size 0 tag component

- .changeset/healthy-tables-check.md
- packages/layout/src/Box/Box.constants.ts
- packages/layout/src/Box/Box.styles.css
- packages/layout/src/Box/Box.types.ts
- packages/menu/src/Menu/Menu.tsx
- Add z-index prop support to `<Box/>` component
- Correct menu zIndex pro
[KNO-6311](https://linear.app/knock/issue/KNO-6311/[telegraph]-add-z-index-prop-to-box-component)
> feat: add z-index prop to box + fix menu z-index

- .storybook/main.ts
- package.json
- yarn.lock
- Adds vanilla extract vite plugin to storybook config to properly compile styles
[KNO-6362](https://linear.app/knock/issue/KNO-6362/[telegraph]-add-vanilla-extract-vite-plugin-to-storybook)
> chore: add vanilla-extract plugin to storybook vite config

- .changeset/four-roses-refuse.md
- packages/button/src/Button/Button.css.ts
- packages/postcss-config/src/style-engine-postcss-config.ts
- CSS selectors with data attributes was incorrect
- Post CSS combining like selectors was leading to classes being incorrectly combined and breaking active state
[KNO-6402](https://linear.app/knock/issue/KNO-6402/[telegraph]-fix-nesting-on-build-in-style-engine-build)
> fix: button active state target + css build issues

- .changeset/friendly-days-drop.md
- packages/modal/src/Modal/Modal.tsx
- packages/tokens/src/tokens/spacing.ts
Updates modal max width based on QA feedback from Krisna.
> fix: update modal max width to 640px

- .changeset/chatty-sloths-chew.md
- package.json
- packages/combobox/package.json
- packages/combobox/src/Combobox/Combobox.stories.tsx
- packages/combobox/src/Combobox/Combobox.test.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- yarn.lock
- Adds `clearable` prop to combobox to allow for clicking an "X" button to clear the input when set to true. 
- Allows for `value` and `onValueChange` to be passed to the Search input so that you can use a different mechanism to filter the list. 
[KNO-6816](https://linear.app/knock/issue/KNO-6816/[telegraph]-add-clear-button-controlled-search-to-combobox)
> feat: combobox controllable search field + clearable

- .changeset/hip-bats-burn.md
- packages/kbd/src/Kbd/Kbd.helpers.ts
- Adds icons for directional arrow keys to `<Kbd/>`
[KNO-7272](https://linear.app/knock/issue/KNO-7272/[telegraph]-add-arrow-key-icons-to-kbd-component)
> feat: add directional arrow keys to kbd component

- .changeset/nasty-shoes-flow.md
- packages/layout/src/Box/Box.constants.ts
- packages/layout/src/Box/Box.styles.css
- packages/typography/src/constants.ts
- There were a few options missing from the Box component that were causing issues in our use case of telegraph. These add those to fix said regressions.
KNO-7702
> fix: regressions from style-engine upgrade

- .changeset/weak-impalas-joke.md
- packages/combobox/src/Combobox/Combobox.stories.tsx
- packages/combobox/src/Combobox/Combobox.tsx
> fix(KNO-7805): Fix typo in combobox CSS vars

- .changeset/itchy-queens-visit.md
- packages/tokens/src/tokens/spacing.ts
Used for guides start/end time popover width
> feat: add 120 to spacing constants for popover width

- .changeset/nasty-planes-rush.md
- packages/combobox/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/popover/package.json
- packages/segmented-control/package.json
- packages/tabs/package.json
- yarn.lock
- Updates ALL radix dependencies to latest versions
[KNO-9016](https://linear.app/knock/issue/KNO-9016/telegraph-update-radix-deps)
> chore: upgrade all radix deps

- .github/dependabot.yml
- packages/appearance/package.json
- packages/button/package.json
- packages/combobox/package.json
- packages/compose-refs/package.json
- packages/filter/package.json
- packages/helpers/package.json
- packages/icon/package.json
- packages/input/package.json
- packages/kbd/package.json
- packages/layout/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/nextjs/package.json
- packages/popover/package.json
- packages/radio/package.json
- packages/segmented-control/package.json
- packages/select/package.json
- packages/style-engine/package.json
- packages/tabs/package.json
- packages/tag/package.json
- packages/textarea/package.json
- packages/tokens/package.json
- packages/tooltip/package.json
- packages/truncate/package.json
- packages/typography/package.json
- packages/vite-config/package.json
- yarn.lock
Latest vite upgrade broke storybook, downgrading for now to unblock.
> fix: downgrade vite to fix storybook
