- .github/workflows/commitlint-pr.yml
- .github/workflows/release.yml
Apparently using the GITHUB_TOKEN to push to the changeset branch doesn't trigger actions to run, but using a Personal Access Token does.
source: https://github.com/changesets/action/issues/70
> fix: change action token to let jobs run bot generated pr

- .changeset/funny-papayas-wink.md
- packages/typography/src/Heading/Heading.test.tsx
- packages/typography/src/Heading/Heading.tsx
- packages/typography/src/Text/Text.test.tsx
- packages/typography/src/Text/Text.tsx
`@telegraph/typography`
- Fixes type issues in existing tests
- Fixes letting the `className` prop through to the component
- Adds the Text Component
> feat: text component

- .changeset/wise-donkeys-exist.md
- packages/typography/README.md
- packages/typography/src/Heading/Heading.tsx
- packages/typography/src/Text/Text.tsx
- packages/typography/src/helpers/prop-mappings.ts
The new button component needs a few new colors to exist in our typography components in order to work.
`@telegraph/typography`
- Adds `white` and `disabled` colors to typography components
- Changes `black` to `default` to match figma
- Updates docs
> feat: add new typography colors to support button component

- .changeset/nice-lies-taste.md
- packages/typography/src/Heading/Heading.tsx
- packages/typography/src/Text/Text.tsx
The `as` prop wasn't properly updating the underlying component.
- Modifies `Heading` & `Text` components to utilize the as prop in the underlying component
- Updates type defs to support the different elements
> fix: as prop updates typography components to correct element

- packages/tag/src/Tag/Tag.tsx
`@telegraph/tag`
- Fix the types being referenced for color & variant so it reflects the constants in the component
> fix: tag component type issue

- packages/button/src/Button/Button.tsx
`@telegraph/button`
- Adds `as` prop to Button so that we can pass other components to be used in place of a standard "button". This also uses a typescript generic so that we can cast the passed in `as` component's props onto the button. For example, when passing a Next.js Link through the `as` prop, you'll get `href`, `shallow`,`scroll`, etc, props automatically.
> feat: as prop on button

- .changeset/smooth-tips-grab.md
- packages/button/src/Button/Button.tsx
- packages/helpers/.eslintrc.js
- packages/helpers/README.md
- packages/helpers/package.json
- packages/helpers/src/index.ts
- packages/helpers/src/types/utility.ts
- packages/helpers/tsconfig.json
- packages/helpers/vite.config.mts
- packages/input/package.json
- packages/input/src/Input/Input.tsx
- packages/layout/src/Box/Box.tsx
- packages/tag/package.json
- packages/tag/src/Tag/Tag.tsx
- yarn.lock
When @connorlindsey was adding in the `Tag` component to control we were noticing a few minor type issues with required vs optional props. This fixes those type issues and also adds in a `@telegraph/helpers` package where we can re-use types like this across telegraph for more consistency.
> fix: tag type issues + add helper types

- .changeset/thick-dogs-study.md
- packages/layout/src/Stack/Stack.constants.ts
The gap variable on `<Stack/>` was using a static css variable when it should be pointing to using our tokens store in css variables instead. 
[KNO-5950](https://linear.app/knock/issue/KNO-5950/[telegraph]-fix-gap-not-using-css-variable)
> fix: stack gap not using css variable tokens

- .changeset/rotten-apples-beam.md
- examples/playground/app/page.tsx
- packages/button/src/Button/Button.stories.tsx
- packages/button/src/Button/Button.test.tsx
- packages/icon/README.md
- packages/icon/package.json
- packages/icon/src/Icon/Icon.constants.ts
- packages/icon/src/Icon/Icon.stories.tsx
- packages/icon/src/Icon/Icon.styles.css
- packages/icon/src/Icon/Icon.test.tsx
- packages/icon/src/Icon/Icon.tsx
- packages/icon/src/default.css
- packages/icon/src/index.ts
- packages/input/src/Input/Input.stories.tsx
- packages/tag/README.md
- packages/tag/src/Tag/Tag.stories.tsx
- packages/tag/src/Tag/Tag.tsx
- packages/vite-config/src/vite-config.ts
- yarn.lock
- Replaces `ionicons` with `lucide-react`
- Reconfigures `@telegraph/icon` to work with `lucide-react`
- Updates components utilizing `@telegraph/icon` to work with breaking changes.
- Fixes tests / Fixes usages in storybook
Notes:
- This work supports [KNO-5961](https://linear.app/knock/issue/KNO-5961/[dashboard]-update-codeeditor-icons-to-lucide-icons) and will require changes to be made in control where we're utilizing `@telegraph/icon`. Builds will fail on this new version in control until updates are made, so zero risk on breakages making it to production.
[KNO-6062](kyle-kno-6062-telegraph-update-icon-component-to-use-lucide-icons)
> feat: migrate to lucide icons

- .storybook/global.css
- .storybook/main.ts
- package.json
- yarn.lock
- Updates storybook css import to be `default` so we get theme-ing
- Adds storybook addon to control color scheme to switch between themes
[KNO-6149](https://linear.app/knock/issue/KNO-6149/[telegraph]-light-dark-mode-support-in-storybook)
> feat: add render modes for light / dark support in storybook

- .changeset/seven-clouds-applaud.md
- packages/icon/src/Icon/Icon.tsx
- If an icon is only used for decoration the `alt` prop should not be required. So, if passing `aria-hidden` to the Icon, the `alt` prop becomes optional as this is the correct prop to pass to adhere to a11y standards.
[KNO-6152](https://linear.app/knock/issue/KNO-6152/[telegraph]-icon-optional-alt-when-passing-aria-hidden)
> feat: icon alt prop optional when aria-hidden is present

- packages/tokens/src/tokens/spacing.ts
- Adds spacing unit `160` (`40rem` / `640px`) to use as the default width for cards
[KNO-6153](https://linear.app/knock/issue/KNO-6153/[telegraph]-640px-spacing-constant)
> feat: add spacing token for card wdith

- .gitignore
- .moon/workspace.yml
- package.json
- templates/package/.eslintrc.js
- templates/package/README.md
- templates/package/package.json
- templates/package/postcss.config.mjs
- templates/package/src/default.css
- templates/package/tailwind.config.mts
- templates/package/template.yml
- templates/package/tsconfig.json
- templates/package/vite.config.mts
- templates/package/vitest.config.mts
- templates/package/vitest.d.ts
- yarn.lock
- Adds the ability to scaffold a new project via cli command `yarn generate:package`
- Uses [moonrepo](https://moonrepo.dev/docs/guides/codegen#generating-code-from-a-template) for code generation
- Adds `package` template
[KNO-6151](https://linear.app/knock/issue/KNO-6151/[telegraph]-add-scaffolding-commands-for-packages)
> feat: package scaffolding with moonrepo

- .storybook/main.ts
- package.json
- postcss.config.js
- yarn.lock
The post css config added to the root directory for storybook was being used as the default for the package css config in weird scenarios. This remove the post css config and instead inlines the config in storybook's vite config.
[KNO-6175](https://linear.app/knock/issue/KNO-6175/[telegraph]-fix-post-css-config)
> fix: pkg postcss config collidng with storybook postcss config

- .changeset/wet-toys-prove.md
- packages/button/src/Button/Button.test.tsx
- packages/icon/src/Icon/Icon.tsx
Missing alt text would still throw a runtime error even if aria hidden is set to true. Also adds a test to check that behavior.
> fix: don't throw error if alt text is missing for aria hidden icon

- .changeset/red-baboons-warn.md
- packages/layout/src/Stack/Stack.tsx
- Fixes the props from `<Box/>` not being properly inherited into the `<Stack/>` component. `React.ComponentPropsWithoutRef` seems like it might be bugged, you can see Radix uses their own custom type for this [here](https://github.com/radix-ui/primitives/blob/af1e3b41cb5c49d7b8c073d2aec34d5074c6dd17/packages/react/primitive/src/Primitive.tsx#L28), so `React.ComponentProps` seems to work fine for this for now. 
[KNO-6155](https://linear.app/knock/issue/KNO-6155/[telegraph]-stack-not-properly-inheriting-box-props-in-typescript)
> fix: box props not inherited through stack component

- .changeset/late-drinks-roll.md
- packages/button/src/Button/Button.tsx
- packages/helpers/src/index.ts
- packages/helpers/src/types/utility.ts
- packages/icon/src/Icon/Icon.tsx
- packages/input/package.json
- packages/input/src/Input/Input.tsx
- packages/layout/src/Box/Box.tsx
- packages/layout/src/Stack/Stack.tsx
- packages/modal/src/Modal/Modal.tsx
- packages/radio/src/RadioCards/RadioCards.tsx
- packages/tag/src/Tag/Tag.tsx
- packages/typography/package.json
- packages/typography/src/Code/Code.tsx
- packages/typography/src/Heading/Heading.tsx
- packages/typography/src/Text/Text.tsx
- yarn.lock
- Adds type utilities `PolymorphicProps`, `PolymorphicPropsWithTgphRef`, `TgphComponentProps`, and `TgphElement` to manage `as` and custom `ref` across telegraph
- Removes `forwardRef` when interacting with Telegraph components and replaces with `as` / `tgphRef` combo..
Allows for the ability to use `as` prop across any Telegraph component and get type safe props, for example: `<Text as={motion.span}/>` would get `motion` props like `animate`, `transition`, etc. 
[KNO-6183](https://linear.app/knock/issue/KNO-6183/[telegraph]-refactor-forwardref-to-use-custom-ref-prop)
> feat: better type support with as prop + custom ref

- .changeset/five-rings-float.md
- packages/tag/package.json
- packages/tag/src/Tag/Tag.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
- yarn.lock
- Adds Tooltip for Tag onCopy button
- Refactors some positioning to not use refs
[KNO-6200](https://linear.app/knock/issue/KNO-6200/[telegraph]-add-tooltip-to-tag-buttons)
> feat: add tooltip to tag copy button

- .changeset/empty-snakes-vanish.md
- packages/modal/src/Modal/Modal.tsx
The Radix docs seemed to incorrectly layout the example dialog in a way that doesn't allow for scrolling inside of it. Wrapping the Overlay around the content seems to fix that issue, see; https://github.com/radix-ui/primitives/pull/2250#issuecomment-1777464051
[KNO-6257](https://linear.app/knock/issue/KNO-6257/[dashboard]-unable-to-scroll-in-editor-pop-out)
> fix: modal not allowing for internal scrolling

- .changeset/clever-shoes-mix.md
- .changeset/sharp-suits-rest.md
- packages/layout/src/Stack/Stack.tsx
- packages/menu/src/Menu/Menu.tsx
- packages/tag/src/Tag/Tag.tsx
- Was incorrectly not passing a generic to the `<Root/>` component of `<Tag/>` which lead to the `as` prop being undefined and the type too complex to represent. This now passes that generic.
- Fixes other type issues that were happening during build
[KNO-6263](https://linear.app/knock/issue/KNO-6263/[telegraph]-tag-type-too-complex-to-represent)
> fix: pass generic to tag root to avoid complex type error + other build type errors

- .changeset/mean-kangaroos-beg.md
- packages/modal/src/Modal/Modal.tsx
- Adds container to modal content that gives guardrails on width / height when using `maxW="full"` `w="full"` props on `Modal.Root`
[KNO-6268](https://linear.app/knock/issue/KNO-6268/[telegraph]-modal-max-width-stretching-to-screen)
> fix: modal sizing when full width

- .changeset/old-ways-know.md
- packages/tooltip/src/Tooltip/Tooltip.tsx
Removes the arrow from the tooltip 😀
[Discussion](https://knocklabs.slack.com/archives/C01Q4R82QAU/p1719410520105899)
[KNO-6288](https://linear.app/knock/issue/KNO-6288/[telegraph]-remove-arrow-from-tooltip)
> chore: remove tooltip arrow

- .changeset/sharp-brooms-swim.md
- packages/combobox/src/Combobox/Combobox.tsx
- packages/menu/package.json
- packages/menu/src/Menu/Menu.stories.tsx
- packages/menu/src/Menu/Menu.tsx
- packages/tooltip/src/Tooltip/Tooltip.stories.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
- yarn.lock
- Change `Menu.Anchor` to `Menu.Trigger` for consistency
- Make `Menu` state controllable
- Add `enabled` prop to tooltip for hiding/showing the tooltip 
- Update `Combobox` to use `Menu.Trigger`
[KNO-6304](https://linear.app/knock/issue/KNO-6304/[telegraph]-menu-and-tooltip-fixes)
> fix: menu trigger, tooltip enabled

- .changeset/dry-shrimps-jog.md
- packages/layout/package.json
Adds `@telegraph/style-engine` as dep to `@telegraph/layout`
[KNO-6358](https://linear.app/knock/issue/KNO-6358/[telegraph]-dependabot-upgrades-for-telegraph-tooltipradio-failing)
> fix: add style-engine as dep for layout

- .changeset/clever-badgers-travel.md
- packages/menu/src/Menu/Menu.tsx
- Fixes the `align` style-engine prop from overlapping with the `align` radix prop
- Fixes `border` prop to be `px` from breaking change from style-engine
[KNO-6361](https://linear.app/knock/issue/KNO-6361/[telegraph]-fix-overlapping-align-props-in-menu)
> fix: align prop overlapping + border prop incorrect value

- .changeset/ten-windows-call.md
- packages/button/postcss.config.mjs
- packages/layout/postcss.config.mjs
- packages/postcss-config/src/index.ts
- packages/postcss-config/src/style-engine-postcss-config.ts
Post css build was throwing a warning about not being able to nest. This was due to the tailwind config. This creates a new post css config for the style engine components so that we can get proper nesting
[KNO-6393](https://linear.app/knock/issue/KNO-6393/[telegraph]-fix-button-active-state)
> fix: remove tailwind post css config to get proper nesting

- .changeset/unlucky-ligers-cheat.md
- packages/layout/src/Box/Box.css.ts
- packages/layout/src/Box/Box.tsx
Adds missing border shorthand to box and fixes defaults in Box.tsx
[KNO-6454](kyle-kno-6454-telegraph-add-border-prop-to-box)
> fix: add border shorthand to box

- .changeset/plenty-keys-own.md
- packages/appearance/src/useAppearance.tsx
- packages/kbd/.eslintrc.js
- packages/kbd/README.md
- packages/kbd/package.json
- packages/kbd/postcss.config.mjs
- packages/kbd/src/Kbd/Kbd.constants.ts
- packages/kbd/src/Kbd/Kbd.hooks.tsx
- packages/kbd/src/Kbd/Kbd.stories.tsx
- packages/kbd/src/Kbd/Kbd.tsx
- packages/kbd/src/Kbd/index.ts
- packages/kbd/src/index.ts
- packages/kbd/tsconfig.json
- packages/kbd/vite.config.mts
- packages/typography/src/helpers/prop-mappings.ts
- yarn.lock
Co-authored with @meryldakin 
- Adds `Kbd` component to display keyboard keys with a pressed state
- Adds `KbdProvider` so that a user can wrap parts of their app in order to limit the amount of event listeners, i.e. no `KbdProvider` means and event listener for each use of `Kbd` vs using `KbdProvider` means 1 event listener for all `Kbd` components. 
- Fixes issue with `useAppearance` props
[KNO-6208](https://linear.app/knock/issue/KNO-6208/[telegraph]-kbd-component-pressed-state)
> feat: kbd component

- .changeset/cyan-horses-relate.md
- packages/tooltip/package.json
- packages/tooltip/src/Tooltip/Tooltip.hooks.tsx
- packages/tooltip/src/Tooltip/Tooltip.stories.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
- packages/tooltip/src/Tooltip/index.ts
- packages/tooltip/src/index.ts
- yarn.lock
- Adds `TooltipGroupProvider` to `@telegraph/tooltip` so tooltips can be aware of each other and not delay/animate after a previous tooltip was recently hovered. See: https://x.com/BenMcMahen/status/1816239771271750077
[KNO-6639](https://linear.app/knock/issue/KNO-6639/[telegraph]-tooltip-group-delay)
> feat: tooltip group hover functionality

- .changeset/fuzzy-flowers-know.md
- packages/button/package.json
- packages/button/src/Button/Button.css.ts
- packages/button/src/Button/Button.stories.tsx
- packages/button/src/Button/Button.tsx
- packages/style-engine/src/index.ts
- yarn.lock
- Adds spinner to `state === 'loading'` in the default button
- Removes unused states
[KNO-6641](https://linear.app/knock/issue/KNO-6641/[telegraph]-button-loading-state)
> feat: button loading state

- .changeset/few-lizards-double.md
- packages/radio/src/RadioCards/RadioCards.styles.css
- packages/radio/src/RadioCards/RadioCards.tsx
- packages/radio/src/default.css
Updates the text/icon colors for the unselected, hover, and active states. Also updates the spacing between cards. 
Looks like the built css is correct too:
> fix: update radio card color styles and spacing

- .changeset/moody-hotels-repeat.md
- packages/button/src/Button/Button.css.ts
- packages/button/src/Button/Button.tsx
- Consolidates logic for the buttons `state`
- Updates css targets for disabled and active to target based on the data attribute, so that disabled can be utilized without having the side effects of styling the button as disabled.
- Loading state can now be turned on without giving the user the ability to click the button
[KNO-6648](https://linear.app/knock/issue/KNO-6648/[telegraph]-disable-button-when-in-loading-state)
> feat: disable button when in loading state + refactor button state management

- .changeset/tame-planes-double.md
- packages/button/src/Button/Button.tsx
- packages/helpers/src/hooks/useDeterminateState.ts
- packages/helpers/src/index.ts
Adds `useDeterminateState` hook, allowing a state value to hold a certain value for a minimum amount of time. For example, this hook is integrated into our button component so that if the `state` prop is set to `loading`, it will remain `loading` for at least 1 second, even if `state` transitions to another value. This ensures that the button cleanly transitions to a `loading` state and remains visible long enough for the user to perceive it, even if the action takes a shorter amount of time than the `minDurationMs`.
[KNO-6656](https://linear.app/knock/issue/KNO-6656/[telegraph]-usedeterminatestate-hook-button-integration)
> feat: useDeterminateState + button integration

- .changeset/four-insects-play.md
- packages/button/src/Button/Button.tsx
Previously, the button loading state was only applicable if you were using the default button export. This wasn't ideal as we'd want the loading state reflected no matter how you are using the button. 
So, this update moves the `useDeterminateState` hook into the Root component and also the rendering of the loading icon. It also adds logic for hiding the `leadingIcon` when the button is in a loading state so that the loading state can replace that icon. This is in line with the original spec provided by Krisna, ensuring it works as intended.
[KNO-6662](https://linear.app/knock/issue/KNO-6662/[telegraph]-refactor-button-loading-state-to-be-more-flexible)
> feat: refactor button loading state to be more flexible

- .changeset/quiet-impalas-clean.md
- packages/helpers/package.json
- packages/helpers/src/components/RefToTgphRef/RefToTgphRef.tsx
- yarn.lock
When in dev mode in control, the console became littered with the warning `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()`. This was happening because we were always passing the `ref` from `React.fowardRef` into the underlying component via radix `<Slot/>`. This PR refactors the `RefToTgphRef` component to detect if the children contain `React.forwardRef` and ONLY pass `ref` under that circumstance. This totally eliminates the warning while still maintaining the ability to pass `ref` to components outside of the telegraph ecosystem. Doing this refactor will also allow us to more granularly control how refs are passed when we eventually need to support React v19. …
> fix: ref warning from RefToTgphRef

- .changeset/real-sheep-bathe.md
- packages/menu/src/MenuItem/MenuItem.tsx
Should fix the width of custom combobox option labels for the message type picker
> fix: make menu item stack full width

- .changeset/six-islands-sleep.md
- packages/radio/src/RadioCards/RadioCards.stories.tsx
- packages/radio/src/RadioCards/RadioCards.tsx
This PR updates `RadioCards` so that:
- The `RootProps` type reflects the fact that `Stack` props can be passed in. (This allows us to set a `direction` prop on the `RadioCards` component.)
- When the `options` prop is used, the layout of rendered card items will depend upon the `direction` of the root `RadioCards` component.
https://github.com/user-attachments/assets/8b3bea65-1b57-40b6-8a8c-dc7d469e08b3
> feat: update RadioCards to support direction

- .changeset/dry-peas-travel.md
- packages/appearance/src/index.ts
- packages/appearance/src/useAppearance.tsx
- packages/button/src/Button/Button.css.ts
- packages/button/src/Button/Button.test.tsx
- packages/button/src/Button/Button.tsx
- packages/tooltip/src/Tooltip/Tooltip.constants.ts
- packages/tooltip/src/Tooltip/Tooltip.stories.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
- Allows an `appearance` prop to be set on a tooltip with the default set to `dark`. This helps to support cases where we want to override the theme of the tooltip like in the `DateTimePopover`
- Adds an `OverrideAppearance` helper component to `@telegraph/appearance` to support this work. 
- Adds the `appearance` prop to storybook to test this behavior.
- Previously, we relied on `pointer-events: none` when `disabled` was set to block all `<Button/>` click events. This worked great for that, but not so great when we wanted things like hover events to trigger tooltips. This PR fixes this issue by removing the `pointer-events: auto` style and instead relies on the native button disabled state. For example, when passing `as={Link}` _or_ `as="a"` along with `disabled={true}`, we now override …
> feat: various tooltip improvements and fixes

- .changeset/rude-lions-fly.md
- packages/tooltip/src/Tooltip/Tooltip.tsx
Removes the extra span from the disabled tooltip. Seems to be causing minor layout changes when the tooltip was enabled/disabled with the following markup:
```
<Stack>
<Button />
<Tooltip enabled={isEnabled} label={...}>
<Button />
</Tooltip>
</Stack>
```
When disabled, the span was adding 2px around the right button. Cannot track down why that is (there's no border, etc. - the span shouldn't be affecting anything), but I think not adding the extra span is cleaner regardless.
> fix: only render children when Tooltip is disabled

- .changeset/flat-gifts-compare.md
- packages/radio/src/RadioCards/RadioCards.tsx
This PR fixes keyboard control of radio card components, namely the ability to use the left and right arrow keys (or up and down arrow keys) to change which radio item within a group is focused and checked. See [the Keyboard Interaction section of the Radio Group Pattern page in the ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/radio/).
As per [Radix’s _Composition_ docs](https://www.radix-ui.com/primitives/docs/guides/composition#your-component-must-forward-ref), when the `asChild` prop is used, children of `RadioGroup.Root` and `RadioGroup.Item` must accept a ref. Telegraph components use `tgphRef` rather than `ref`, so we simply need to wrap the child components in `<RefToTgphRef>` to apply the forwarded ref to `tgphRef`. …
> fix(KNO-7179): radio card keyboard interactions

- .changeset/afraid-jeans-occur.md
- packages/textarea/.eslintrc.js
- packages/textarea/README.md
- packages/textarea/package.json
- packages/textarea/postcss.config.mjs
- packages/textarea/src/TextArea/TextArea.constants.ts
- packages/textarea/src/TextArea/TextArea.css.ts
- packages/textarea/src/TextArea/TextArea.stories.tsx
- packages/textarea/src/TextArea/TextArea.tsx
- packages/textarea/src/TextArea/index.ts
- packages/textarea/src/index.ts
- packages/textarea/tsconfig.json
- packages/textarea/vite.config.mts
- packages/textarea/vitest.config.mts
- yarn.lock
- Adds `<TextArea/>` component based on the [figma doc](https://www.figma.com/design/br4Lk9C5qw3UVyGsAbONDY/Telegraph-design-system?node-id=893-1686&m=dev)
- Utilizes `@telegraph/style-engine` and `<Box/>` for styling
- Exports `<TextArea/>` props via `TextAreaProps` 
[KNO-6105](https://linear.app/knock/issue/KNO-6105/[telegraph]-text-area-component)
> feat: textarea component

- .changeset/sharp-mirrors-watch.md
- packages/combobox/package.json
- packages/combobox/src/Combobox/Combobox.stories.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- yarn.lock
- Wraps `<Combobox.Content/>` in radix's `<DismissableLayer/>` so that "Escape" key presses are swallowed by the `<DissmissableLayer/>` as to not bubble up to the `<Combobox/>` parent. This prevents instances when a user is in a `<Modal/>` pressing "Escape" to close the `<Combobox/>` and it instead closes the `<Modal/>`
[KNO-7063](https://linear.app/knock/issue/KNO-7063/[telegraph]-cant-get-out-of-combobox-dropdown-w-keyboard)
> fix: close combobox without closing parent

- packages/button/src/Button/Button.stories.tsx
- packages/combobox/src/Combobox/Combobox.stories.tsx
- packages/icon/src/Icon/Icon.stories.tsx
- packages/input/src/Input/Input.stories.tsx
- packages/kbd/src/Kbd/Kbd.stories.tsx
- packages/menu/src/Menu/Menu.stories.tsx
- packages/menu/src/MenuItem/MenuItem.stories.tsx
- packages/modal/src/Modal/Modal.stories.tsx
- packages/popover/src/Popover/Popover.stories.tsx
- packages/radio/src/RadioCards/RadioCards.stories.tsx
- packages/segmented-control/src/SegmentedControl/SegmentedControl.stories.tsx
- packages/tag/src/Tag/Tag.stories.tsx
- packages/tooltip/src/Tooltip/Tooltip.stories.tsx
- Adds autodocs tag to every `.stories` file in the repo
- Small updates to get the code formatting in `.stories` to work correctly.
[KNO-7237](https://linear.app/knock/issue/KNO-7237/[telegraph]-add-auto-docs-similar-structure-as-text-area-to-all)
> feat: add autodocs to storybook components

- .changeset/mean-roses-type.md
- packages/combobox/src/Combobox/Combobox.helpers.ts
- packages/combobox/src/Combobox/Combobox.test.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/select/.eslintrc.js
- packages/select/README.md
- packages/select/package.json
- packages/select/postcss.config.mjs
- packages/select/src/Select/Select.stories.tsx
- packages/select/src/Select/Select.tsx
- packages/select/src/Select/index.ts
- packages/select/src/index.ts
- packages/select/tsconfig.json
- packages/select/vite.config.mts
- packages/select/vitest.config.mts
- yarn.lock
- Adds `<Select/>` component. A simpler version of `<Combobox/>` that more closely matches the browser `<select/>` element.
- Support the `multiple` prop like the browser `<select/>`
- Fixes [KNO-6849](https://linear.app/knock/issue/KNO-6849/[telegraph]-allow-combobox-labels-to-be-react-nodes) so that we can pass react nodes to the label.
- Fixes [KNO-6934](https://linear.app/knock/issue/KNO-6934/[telegraph]-allow-disabled-state-without-type-error-on-combobox) so that we can pass the `disabled` prop to the select component and combobox component.
[KNO-7249](https://linear.app/knock/issue/KNO-7249/[telegraph]-select-component)
[KNO-6934](https://linear.app/knock/issue/KNO-6934/[telegraph]-allow-disabled-state-without-type-error-on-combobox) …
> feat: select component

- .changeset/silly-buses-prove.md
- packages/modal/src/Modal/Modal.stories.tsx
- packages/modal/src/Modal/Modal.tsx
- The `FocusTrap` component was inserting a `div`. Adding the `asChild` prop + wrapping `Stack` in the ref convertor allows there to be only a single div now. 
- Added `overflowY: "auto"` to `Modal.Body` as default. 
- Added a modal with a lot of content in storybook so we can see if this behavior works as expected.
[KNO-7270](https://linear.app/knock/issue/KNO-7270/[telegraph]-fix-modal-overflow-issue)
> fix: modal overflow issue

- .changeset/six-turtles-scream.md
- packages/modal/src/Modal/Modal.stories.tsx
- packages/modal/src/Modal/Modal.tsx
- Changes the modal structure to always house modals inside of a `Portal`.
- Updates how `FocusScope` was added to the component allowing for better control of trapping and allowing for props to be passed to it. 
[KNO-7292](https://linear.app/knock/issue/KNO-7292/[telegraph]-overlapping-modal-w-code-editor-is-broken)
> fix: improve modal stacking with portal

- .changeset/violet-zebras-roll.md
- packages/button/src/Button/Button.tsx
We missed adding `whiteSpace: nowrap` to the text in buttons after the tailwind migration.
[KNO-7332](https://linear.app/knock/issue/KNO-7332/[telegraph]-make-button-text-not-wrap)
> fix: button text wrapping

- .changeset/rare-mayflies-shake.md
- packages/tag/src/Tag/Tag.tsx
Text in the `<Tag/>` component would wrap two lines if it was too long. This adds a sensible default `max-width` for the text to wrap to with the ability to set also explicitly set the `max-width`.
[KNO-7313](https://linear.app/knock/issue/KNO-7313/[dashboard]-workflow-key-wraps-when-too-long)
> fix: truncate tag text instead of wrapping

- .changeset/gold-adults-draw.md
- packages/style-engine/src/helpers/getStyleProp/getStyleProp.ts
- packages/style-engine/src/hooks/useStyleEngine.ts
- Read-only errors will sometimes appear in dev mode when assigning a value to an existing item. This change should suppress that issue.
KNO-7742
> fix: read-only warning in dev mode

- .changeset/bright-chairs-mix.md
- packages/combobox/src/Combobox/Combobox.tsx
This PR updates `Combobox.Options` so that the default stack max height of `calc(var(--tgph-combobox-content-available-height) - var(--tgph-spacing-12))` is only applied when a custom `maxHeight` prop is not passed in.
> fix(KNO-7736): support setting maxHeight on Combobox.Options

- .changeset/sour-boxes-breathe.md
- packages/button/src/Button/Button.tsx
We weren't passing the style prop into the `useStyleEngine` hook so any style prop passed into the button would override any styles we set via the hook.
KNO-7748
> fix: persist style prop through button

- .changeset/honest-adults-exercise.md
- .storybook/main.ts
- packages/layout/package.json
- packages/tokens/package.json
- packages/tokens/scripts/generate-css-file.js
- packages/tokens/scripts/generate-css-var-map.js
- packages/vite-config/package.json
- packages/vite-config/src/style-engine-config.ts
- yarn.lock
In an effort to support React 19 with out JS SDK, we have to make sure Telegraph can support React 19 as well, since its a dependency there.
[Here is the major upgrade guide for `vanilla-extract`](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fvite-plugin%405.0.0)
When running `yarn install` on main:
```bash
➤ YN0060: │ vite is listed by your project with version 6.0.11, which doesn't satisfy what @vanilla-extract/vite-plugin (p5b4dc) and other dependencies request (^4.2.0 || ^5.0.0).
```
A step in the process to address [#317](https://github.com/knocklabs/javascript/issues/317) and [KNO-7523](https://linear.app/knock/issue/KNO-7523/[js]-support-react-19-in-react-sdks).
As a first step, I'm going to update the existing peer dependency issues. Next …
> chore: upgrades Vite plugins, fixes peer dependency issues

- vitest/setup.ts
I think we can clean up our vitest setup file a bit. `@testing-library/jest-dom` provides [vitest-specific setup instructions](https://github.com/testing-library/jest-dom/blob/main/README.md#with-vitest). If we import `@testing-library/jest-dom/vitest`, vitest’s `expect` will [automatically be extended with Testing Library’s matchers](https://github.com/testing-library/jest-dom/blob/918b6fbcde10d4409ee8f05c6e4eecbe96a72b7a/vitest.js#L4) and [vitest’s types will be augmented](https://github.com/testing-library/jest-dom/blob/918b6fbcde10d4409ee8f05c6e4eecbe96a72b7a/types/vitest.d.ts#L4-L15).
> chore(KNO-7887): clean up vitest setup file

- .changeset/good-ghosts-rush.md
- packages/layout/src/Box/Box.constants.ts
I noticed some weirdness when adding an `mb` prop to the `<Heading>` component. This fixes it.
> fix(KNO-7992): Fix margin and marginX in Box constants

- .changeset/happy-ducks-clean.md
- packages/menu/src/Menu/Menu.tsx
Fixed  `onClick` support to the Menu Button component. The `{...props}` spreading was passing it out twice and the onClick functions were firing twice.
1. Open the Menu component storybook
2. Click on the "Manage workflow" button in the Default story
3. Verify that "clicked" appears in the console
This change enables interactive functionality for Menu buttons, allowing developers to handle click events. This is a fundamental feature for menus that need to trigger actions when items are selected.
[Linear](https://linear.app/knock/issue/KNO-8209/[telegraph]-menubutton-fires-onclick-events-twice)
> fix: onClick handler no longer fires twice when using Menu.Button component

- packages/filter/.eslintrc.js
- packages/filter/README.md
- packages/filter/package.json
- packages/filter/postcss.config.mjs
- packages/filter/src/Filter/Filter.stories.tsx
- packages/filter/src/Filter/Filter.tsx
- packages/filter/src/Filter/helpers.ts
- packages/filter/src/Filter/index.ts
- packages/filter/src/Filter/types.ts
- packages/filter/src/Filter/useInternalStateController.ts
- packages/filter/src/index.ts
- packages/filter/tsconfig.json
- packages/filter/vite.config.mts
- packages/filter/vitest.config.mts
- packages/menu/src/MenuItem/MenuItem.stories.tsx
- yarn.lock
This component is a WIP. When writing this component originally, I intended to move it into Telegraph further down the line.
Some things I wanted to improve before making this package available:
- Finish styling to match designs
- Better typing to remove `@ts-expect-errors`
- Better flexibility around rendering support component (not just passing in a LucideIcon -- what if we want something else?)
- Better composibility around secondary update (when clicking a Chip, update value -- what kind of component gets shown?)
- Microanimations
- Remove query param for telegraph -- this should be done by consumer by accessing the state
- Add docs
- Add hotkey support
Add a new Filter component package to Telegraph
- Created a new `@telegraph/filter` package with a flexible filter component
- …
> feat(kno-7951): add flexible filter component package

- .changeset/sharp-ants-drive.md
- packages/combobox/src/Combobox/Combobox.stories.tsx
- packages/combobox/src/Combobox/Combobox.test.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/helpers/src/index.ts
- packages/helpers/src/types/utility.ts
- Adds support for passing a custom `children` value (either a React node or a function) to `Combobox.Trigger`, giving you full control over how the trigger is rendered. This is helpful when the trigger’s appearance should differ from the options — for example, if you only want to show a label, display an icon, or format the value in a specific way.
- When using a function, the `children` callback receives the current `value`, and TypeScript will infer its type based on whether the combobox is in single- or multi-select mode. If needed, you can explicitly pass `typeof value` to guide inference.
- Fixes a bug where `Button` and `Menu.Trigger` props weren’t being properly applied to `Combobox.Trigger`.
```tsx
const [value, setValue] = React.useState("value");
return (
<Box w="80"> …
```
> feat: combobox custom trigger

- .changeset/tender-taxis-invite.md
- packages/button/src/Button/Button.tsx
- packages/combobox/README.md
- packages/combobox/src/Combobox/Combobox.helpers.ts
- packages/combobox/src/Combobox/Combobox.primitives.tsx
- packages/combobox/src/Combobox/Combobox.stories.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/combobox/src/Combobox/Combobox.types.ts
- packages/tag/src/Tag/Tag.tsx
- Added `Primitives` to the combobox so you can build custom trigger layouts while still using the built-in trigger parts.
- Refactored the combobox to use these new primitives internally.
- Improved type safety by updating types in some of the existing components.
- Added a detailed README for the combobox, including how to use the new primitives.
[KNO-8287](https://linear.app/knock/issue/KNO-8287/[telegraph]-improve-flexibility-of-combobox-trigger)
> feat: combobox primitive trigger parts

- .changeset/silly-phones-cheat.md
- packages/motion/src/Motion/Motion.tsx
- packages/popover/src/Popover/Popover.stories.tsx
- packages/popover/src/Popover/Popover.tsx
- packages/tooltip/src/Tooltip/Tooltip.stories.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
- In the new template editor, the "Send test" popover animation feels overly pronounced due to its size. To address this, we added a `skipAnimation` prop to `<Motion />` that allows disabling the animation entirely when needed.
- This prop is now integrated into both the `<Popover />` and `<Tooltip />` components to support cases where animation should be skipped.
[KNO-8353](https://linear.app/knock/issue/KNO-8353/[telegraph]-add-ability-to-skip-animations-on-popover-and-tooltips)
> feat: add skipAnimation prop to motion, apply skipAnimation prop to tooltip and popover

- .changeset/ten-dancers-explain.md
- packages/menu/src/MenuItem/MenuItem.tsx
- packages/tabs/README.md
- packages/tabs/src/Tab/Tab.tsx
- packages/tabs/src/TabList/TabList.tsx
- packages/tabs/src/default.css
[Linear issue](https://linear.app/knock/issue/KNO-8457/[telegraph]-fix-spacing-and-font-weight-for-tabs-list-component)
Reduce vertical Y padding and increase fontWeight to 500, matching the figma
> fix(kno-8547): fixes tabs weight and spacing

- .changeset/chilled-boxes-check.md
- packages/button/src/Button/Button.test.tsx
- packages/icon/package.json
- packages/icon/src/Icon/Icon.test.tsx
- packages/icon/src/Icon/Icon.tsx
- packages/icon/src/Icon/Icon.types.ts
- packages/icon/src/Icon/index.ts
- packages/icon/src/index.ts
- vitest/axe.ts
- yarn.lock
The `@telegraph/icon` package exported ALL of the icons from `lucide-react` under the `Lucide` object. In doing the export in this way, a downstream bundler would be unable to successfully tree shake the package making it so ALL of the icons were in the main bundle. This PR utilizes [Lucide's Dynamic Icon Component](https://lucide.dev/guide/packages/lucide-react#dynamic-icon-component) so that during telegraph's bundling process each icon is put into its own file making it so a downstream bundler does not have to treeshake telegraph. This PR also maintains backwards compatibility with the previous `Lucide.Bell` pattern so that no code updates will need to be made by the downstream user.
In this PR we also:
- Update the tests to work with `DynamicIcon`, which required a mocking process …
> feat: decrease icon package downstream bundle size by using lucide dynamic

- .changeset/tiny-mayflies-knock.md
- packages/kbd/src/Kbd/Kbd.helpers.ts
- packages/kbd/src/Kbd/Kbd.tsx
The `<Kbd/>` component relied on `Lucide.IconName` to be an object an not string to decide if it would display an icon or text inside of it. The latest update to `<Icon/>` made it so the value `Lucide.IconName` returns is the kebab cased icon name. This PR updates the `<Kbd/>` component `getIconOrKey` helper to return a different variable based on the type. It also fixes an issue in the case of `appearance` not being defined when then the constants are spread onto the individual components.
> fix: kbd component displaying text instead of icon

- .changeset/slimy-kiwis-laugh.md
- packages/layout/src/Box/Box.styles.css
Currently, when you click an interactive item like `MenuItem` or `Tab`, the background color will stay darker until the user clicks somewhere else.
I think this is annoying. We shouldn't need this styling because we style separately for `active` state. This change makes it so that our custom styles for focusing are only triggered via keyboard, not when the user clicks.
Here is a tab in its current form (click around): https://telegraph-storybook.vercel.app/?path=/story/components-tabs--basic
Here is a tab from this PR (now click around): https://telegraph-storybook-git-mc-change-focus-identifier-knocklabs.vercel.app/?path=/story/components-tabs--basic
> fix: interaction styles dont stick on click

- .changeset/lemon-tomatoes-dance.md
- packages/combobox/src/Combobox/Combobox.tsx
- packages/menu/src/Menu/Menu.tsx
- packages/modal/src/Modal/Modal.tsx
- packages/popover/src/Popover/Popover.tsx
- packages/radio/src/RadioCards/RadioCards.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
- There were a few typescript errors that would throw when running `yarn build:packages`. Some were related to `@radix-ui/react-controllable-state` updating so that `defaultProp` can only be a boolean, the other was just a ref that needed to be typed correctly.
[KNO-9017](https://linear.app/knock/issue/KNO-9017/telegraph-typescript-build-errors)
> fix: typescript build errors

- .changeset/moody-lamps-film.md
- packages/layout/src/Box/Box.styles.css
I forgot to revert the default border on `<Box/>` back to `gray-6` after settings it to `red-6` when debugging things in the tailwind removal PR. This reverts that change 🤦‍♂️ .
> fix: remove debug color as default border

- .changeset/gold-guests-learn.md
- packages/combobox/src/Combobox/Combobox.primitives.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/menu/src/MenuItem/MenuItem.tsx
- packages/modal/src/Modal/Modal.tsx
- packages/popover/src/Popover/Popover.tsx
- packages/tag/src/Tag/Tag.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
I realized I can use a combination of `motion/react-m` and `LazyMotion` + `domAnimation` to reduce the bundle size of packages using `motion` even further. I also went ahead and removed `AnimatePresence` as it's not really doing anything with how our component structure is working.
Here's some more info about reducing bundle sizes with the `motion` package: https://motion.dev/docs/react-reduce-bundle-size
> feat: use motion/react-m and remove animate presence to further reduce bundle sizes

- .github/workflows/code-checks.yml
Attempted to fix an issue where sometimes code checks don't run in a `version packages` pr but this seemed to just make things work, so reverting back.
> fix: ci running back to `pull_request`

- .changeset/large-actors-compete.md
- packages/button/README.md
- packages/button/src/Button/Button.test.tsx
- packages/button/src/Button/Button.tsx
In trying to upgrade the control repo, I found a usecase where we need Button's type prop to be fully compatible with HTML button's type prop.
Also, I forgot to document the prop in readme
**Testing:**
- Add 2 more test cases for comprehensive coverage of 4 potential types
**Verify this package doesn't break control**
In telegraph
`yarn build:packages`
In button directory
`yarn pack`
(copy tgz file version of button to control)
In control
Update `package.json` for `@telegraph/button` to be `"@telegraph/button": "file:package.tgz"`
`yarn install`
`yarn tc` 
No type errors
> fix(KNO-8096): Do not override button "type" prop typing in telegraph button
